[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "triple/x86_64-kine.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"